---
title: 'WIP: Low QALYty Research'
author: 'John L. Preston'
date: '2023-08-04'
output:
  ioslides_presentation:
    widescreen: true
---

<div class="notes">

need to look at DALYs as well as QALYs!

before we begin, content warning
  economics, neoliberalism, health, ableism, ...

examples of headlines, figures, ...
shocking, concerning
all share a common approach to how these figures were constructed

what's a DALY? what's a QALY?
philosophical/ethical problem: saying one life is less valuable than another

how are DALY and QALY coefficients calculated?
EQ-5D
interactive bit
turning 5 numbers into 1 number: value sets and EQ-VT
some states are qualitatively different but have the same valuation/number

how is the cost of a life-year calculated?
curently £70,000 according to DHSC
willingness to pay
interactive bit
thoughts on WTP, problems with this

summary of problems with this approach
reiterate this is critical to (e)valuation and policy making, particularly for public health
what are the alternatives?
  participatory planning
  qualitative research
  ... ???

</div>
